### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by ColossalCalamari** [Sizzzles/TFT-OCR-BOT#28]
Hello. I've been using this bot for many months now with no issue, but with the newest repository version I'm receiving an error when executing main.py. The repository was downloaded from https://github.com/Sizzzles/TFT-OCR-BOT/archive/refs/heads/main.zip . I'm running Python 3.11.4 and have tesserocr-2.6.0 installed.

```
AUTO COMPS TFT OCR BOT started.

Original version - https://github.com/jfd02/TFT-OCR-BOT

AutoComps version - https://github.com/Sizzzles/TFT-OCR-BOT

Close this window to terminate the overlay window & program
Loading champions and comps...
Traceback (most recent call last):
  File "C:\Program Files\TFTBOT\main.py", line 157, in <module>
    main()
  File "C:\Program Files\TFTBOT\main.py", line 152, in main
    auto_comps.load_champions_and_comps(comps_manager)
  File "C:\Program Files\TFTBOT\auto_comps.py", line 225, in load_champions_and_comps
    lol_chess_tftnames_and_price = load_lolchess_prices()
                                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\TFTBOT\auto_comps.py", line 60, in load_lolchess_prices
    find_substring_index(
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Thank you for any help you can provide.

**Comment by jppuzzle** [comment]
I too have the same error

**Comment by Sizzzles** [comment]
This is due to the site updating. Will push a fix when I wake up

**Comment by Sizzzles** [comment]
Should be fixed. Let me know if there are any problems

**Comment by ColossalCalamari** [comment]
Yep, working perfectly now. Thank you!
